package pl.julkot1.yes.exception;

public enum ErrorCodes {
    SUCCESS,
    ARGUMENTS_QUANTITY,
    WRONG_TYPE,
    HEADER_MULTIPLE_IMPORTS,
    HEADER_NOT_MODULE_IMPORT,
    MODULE_FORBIDDEN_STATEMENT_INVOKE,
    TYPE_REQUIRED,
    MV_INVALID_ARRAY,
    STR_TEMPLATE;

}
